# Generated by Django 4.2.21 on 2025-05-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', 'update_storage_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='storage_quota',
            field=models.BigIntegerField(default=1073741824),
        ),
    ]
