# Generated by Django 4.2.21 on 2025-05-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_alter_user_storage_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
